### ISSUE TITLE
Travis builds failing

### ISSUE THREAD

**Issue by eltone** [nesquena/backburner#158]
@nesquena I don't have admin rights for the Travis project, if you add me I'd be happy to look at the failing builds as well.

**Comment by nesquena** [comment]
Looks like https://travis-ci.org/nesquena/backburner/builds/365324979 you can see its just ruby 2.0 failing:

<img width="1072" alt="screen shot 2018-06-11 at 11 23 30 am" src="https://user-images.githubusercontent.com/6511/41249851-1ede6bee-6d6a-11e8-9778-fbcd77d31bb1.png">

I figure we can add to allowed failures because everything else is working fine. If there's an easy fix that would be great too

**Comment by eltone** [comment]
It looks like that build happened 2 months ago though, I don't think any of the recent master commits have been built.

**Comment by nesquena** [comment]
Re-activated now: https://travis-ci.org/nesquena/backburner/builds/390912370

**Comment by eltone** [comment]
Thanks!
