### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by eltone** [nesquena/backburner#161]
Hi @nesquena would you mind creating a new release? There have been quite a few changes since the last and it would be good to get a new one.

**Comment by nesquena** [comment]
Sure, I pushed a 1.5.0 release here: https://rubygems.org/gems/backburner/versions/1.5.0. Could you help me capture the major improvements in master since the last release, at the least the broad strokes: https://github.com/nesquena/backburner/blob/master/CHANGELOG.md. Thanks again for helping keep this project active.
