### ISSUE TITLE
Difference with BeanEater

### ISSUE THREAD

**Issue by matiasgarcia** [nesquena/backburner#168]
Hi @nesquena , I am investigating if using beanstalkd in our ruby apps architecture to have reliability ensured out of the box instead of using other gems that rely on Redis.

I see that there are two projects that use beanstalkd, this one and [beaneater](https://github.com/beanstalkd/beaneater) which seems to also be maintained by you.

Why one should pick one or the other? They seem to be very similar so I am a bit confused.

Thanks!

**Comment by nesquena** [comment]
Beaneater is the underlying beanstalkd client, a bit lower level in terms of how it's used. Backburner is higher level built on top of beaneater itself and intended to mirror other active_job queues in Rails in order to mirror popular queue libraries (https://github.com/rails/rails/tree/master/activejob/lib/active_job/queue_adapters)

Neither are particularly actively maintained, but if it helps I still use backburner in lots of prior projects and it works well for those needs.
